### ISSUE TITLE
Can't build/run on macOS

### ISSUE THREAD

**Issue by get9** [insomniacslk/dhcp#1]
Can't seem to build or run this project on macOS/darwin due to the `syscall.BindToDevice`. Searching around leads me to the SO_BINDTODEVICE sockopt which isn't present on darwin. Instead, others have used a variety of workarounds:
* https://trac.transmissionbt.com/ticket/2313
* http://atastypixel.com/blog/the-making-of-talkie-multi-interface-broadcasting-and-multicast/

**Comment by insomniacslk** [comment]
Thanks for opening this issue. I haven't found an obvious solution as it seems to depend entirely on platform implementations. In the case of Linux we have the best guarantee, i.e. binding to a specific network device, while on macOS and FreeBSD the most we can do appears to be `bind`ing to a specific socket. This is a weaker contract than `SO_BINDTODEVICE` but I guess we can live with the limitation. I will try to get this out this week

**Comment by insomniacslk** [comment]
This might help (as suggested by Marc, who has a better google-fu than I have), https://lists.apple.com/archives/darwin-dev/2014/Jan/msg00004.html .

From the post:
```
you can use IP_BOUND_IF to bind socket to the particular interface index.

something like
int idx = if_nametoindex( "en1");
setsockopt(s, IPPROTO_TCP, IP_BOUND_IF, &idx, sizeof(idx) );
```

**Comment by insomniacslk** [comment]
this seems to work. I'll do some more testing and post a patch here

**Comment by insomniacslk** [comment]
hey @get9 and @rb2k, I've created https://github.com/insomniacslk/dhcp/pull/2 to fix this. I am still testing, but feel free to have a preliminary look
