### ISSUE TITLE
dhcpv4 improvements

### ISSUE THREAD

**Issue by get9** [insomniacslk/dhcp#10]
Seems like the dhcpv4 package isn't as fleshed-out as the dhcpv6 package. A couple improvements:

* `dhcpv4.Client` has a `Timeout` field... but doesn't actually do anything with it
* Couple things could be made as interfaces so they're a little more flexible.

Anything else?

**Comment by insomniacslk** [comment]
There are several other differences. E.g. no option type is defined as a struct, so cannot validate, and it's not easy to access and print; `DHCPv6` is an interface, `DHCPv4` is a struct. And probably several more.

My focus has always been on DHCPv6 and less on DHCPv4 which is a legacy protocol, but I am happy to see and help things improve :)

**Comment by get9** [comment]
First of improvements in #13

**Comment by get9** [comment]
Finished up in #16, #17, #20, #21.
