### ISSUE TITLE
Run gometalinter in CI?

### ISSUE THREAD

**Issue by get9** [insomniacslk/dhcp#104]
[gometalinter](https://github.com/alecthomas/gometalinter) has some pretty high signal about various things that can be improved/fixed, including lots of static analysis on the code. The only one that I think we should probably not run is the cyclomatic complexity linter because there are a lot of spurious warnings (particularly around the parsing func's that have a lot of switch branches).

**Comment by insomniacslk** [comment]
that's a good idea :) let's try it

**Comment by earlgreyz** [comment]
Alternatively to gometalinter I'd recommend [golangci-lint](https://github.com/golangci/golangci-lint) using which is very CI friendly and runs much faster.

**Comment by insomniacslk** [comment]
And yeah, gometalinter has been deprecated in favour of golangci-lint :) I'll definitely add it soon
