### ISSUE TITLE
dhcpv4 user class parsing

### ISSUE THREAD

**Issue by pmazzini** [insomniacslk/dhcp#113]
The user class parsing added in PR #90 does not follow the RFC:

> The value in UC_Len_i does not include the length field itself and MUST be non-zero.

**Comment by pmazzini** [comment]
cc @insomniacslk, @mooneyow

**Comment by pmazzini** [comment]
I may have opened this to soon.
Apparently some clients are sending a non rfc compliant user class option.

**Comment by mooneyow** [comment]
It seems there is a conflicting Microsoft standard where `UC_Len_i` is not included and only one user class can be specified.
https://osqa-ask.wireshark.org/answer_link/55006/

https://msdn.microsoft.com/en-us/library/dd358019.aspx

**Comment by mooneyow** [comment]
https://github.com/insomniacslk/dhcp/pull/114

**Comment by pmazzini** [comment]
Closing this after PR117.
