### ISSUE TITLE
DHCPv6 client use of net.Addr/net.UDPAddr

### ISSUE THREAD

**Issue by gvialetto** [insomniacslk/dhcp#174]
In the DHCPv6 client struct `LocalAddr` and `RemoteAddr` are declared to be of the `net.Addr` type, but wherever they are used the code attempts to cast them to `net.UDPAddr` and return an error on failure.

https://github.com/insomniacslk/dhcp/blob/d17d7ed73609154a9c72e1194a4ad4842447dde8/dhcpv6/client.go#L99-L111

https://github.com/insomniacslk/dhcp/blob/d17d7ed73609154a9c72e1194a4ad4842447dde8/dhcpv6/client.go#L115-L123

Isn't it better to change the struct and have the compiler do this check at compile time instead?

**Comment by pmazzini** [comment]
The new client created by @hugelgupf is no longer using `net.Addr`.
