### ISSUE TITLE
[dhcpv4] iterate over the available options

### ISSUE THREAD

**Issue by pmazzini** [insomniacslk/dhcp#245]
After the changes in PR #227, this won't work:

```
	for k := range pkt.Options {
		switch k {

		case dhcpv4.OptionDHCPMessageType:
```

This doesn't compile because the key of the map is a uint8.

Should the key be changed to an `OptionCode`?

cc @hugelgupf

**Comment by hugelgupf** [comment]
You can use .Code()

**Comment by pmazzini** [comment]
Right! Thanks!
