### ISSUE TITLE
Make TransactionID generation non-blocking

### ISSUE THREAD

**Issue by insomniacslk** [insomniacslk/dhcp#246]
crypto/rand is blocking, while math/rand is not. This blocks the generation of the TransactionID until the machine has enough randomness in the pool. This has been the result of a fun troubleshooting :)

While working on a demo on qemu I found that the DHCPv6 client was apparently stuck. It worked sometimes, it didn't other times. SLAAC was fine and I could see traffic through it. It suddenly started working after a while. The function that generates the TransactionID depends on crypto/rand, that is blocking.

@hugelgupf suggests that Qemu's VirtIORNG could be used, to avoid swapping crypto/rand for math/rand , https://wiki.qemu.org/Features/VirtIORNG .

I would like to discuss in this issue whether it makes sense to enforce a cryptographic RNG or not for Transaction ID generation.

**Comment by hugelgupf** [comment]
It's necessary to use crypto/rand as a way to prevent "MITM" (without the middle). I.e. if you're a malicious actor in your network, and you don't get to see DHCP requests, but you can arbitrarily send responses out... wouldn't it be nice if you could predict the transaction ID?

**Comment by insomniacslk** [comment]
Good point. I'll rather make the generation not to block forever, and fail (configurable)) ift's taking too many rounds or too much time

**Comment by hugelgupf** [comment]
See https://github.com/u-root/u-root/pull/1129

**Comment by hugelgupf** [comment]
see also https://github.com/golang/go/commit/1961d8d72a53e780effa18bfa8dbe4e4282df0b2

in Go 1.12, crypto/rand will print a warning after 60 seconds of blocking.

**Comment by insomniacslk** [comment]
> in Go 1.12, crypto/rand will print a warning after 60 seconds of blocking.

That's how we got it quickly this time :)
