### ISSUE TITLE
OptVendorSpecific is in bsdp package instead of dhcpv4

### ISSUE THREAD

**Issue by insomniacslk** [insomniacslk/dhcp#25]
Shouldn't this be instead in the dhcpv4 package? cc @get9

**Comment by get9** [comment]
Ah nope, I purposefully put it in bsdp because:
1) It's very bsdp-specific
2) (more importantly) There can be multiple different uses of the vendor-specific information fields, ergo it makes more sense for that to be in the more specific package.

**Comment by insomniacslk** [comment]
for some reason I confused this specific vendor option with a generic vendor opt implementation, nevermind!
