### ISSUE TITLE
Swap out netlink library

### ISSUE THREAD

**Issue by hugelgupf** [insomniacslk/dhcp#257]
The most used netlink library out there kind of plays fast and loose with unsafe pointers, sometimes leading to memory corruption.

(E.g. https://github.com/vishvananda/netlink/blob/master/ioctl_linux.go#L89 - should be using binary marshaling instead, since `e` may be freed anytime after - luckily, it gets returned and used *after* Ifreq is given to a syscall, but this kind of stuff is all over that codebase.)

It's also a huge grab-bag of netlink code, which means it's quite a large dependency in our embedded environment. I'd like to recommend switching to a netlink library based on https://github.com/mdlayher/netlink, such as https://godoc.org/github.com/jsimonetti/rtnetlink, which is more targeted (and has no memory corruption).

I'm happy to do this switch when I get to these items.

**Comment by mdlayher** [comment]
https://gitlab.com/mergetb/tech/rtnl is another one being built on my netlink package. I'm unsure of the completion or maturity of either at this point, as I haven't had to do any rtnetlink work in some time.

**Comment by insomniacslk** [comment]
After the fixes at https://github.com/jsimonetti/rtnetlink/pull/17 and https://github.com/jsimonetti/rtnetlink/issues/18 I started working on swapping vishvananda/netlink with jsimonetti/netlink. Work-in-progress at https://github.com/insomniacslk/dhcp/pull/271.
