### ISSUE TITLE
dhcp4 client always wrong "got context deadline exceeded"

### ISSUE THREAD

**Issue by deanchou** [insomniacslk/dhcp#307]
`	iface := "eth0"
	client := client4.NewClient()
	conversation, err := client.Exchange(iface)
	for _, packet := range conversation {
		log.Print(packet.Summary())
	}
	if err != nil {
		log.Fatal(err)
	}`

get an error "could not get random number: got context deadline exceeded"

**Comment by insomniacslk** [comment]
this means your system's RNG cannot generate random numbers within a certain deadline. Are you using virtualization without a virtio RNG attached?

**Comment by deanchou** [comment]
Yes, I found a solution.
I think crng is ignored in kernel initialization,because i didn't find "crng init done'
Thank you very much for your reply
