### ISSUE TITLE
need to implement myself if i want to send a decline message from client side

### ISSUE THREAD

**Issue by futureday2015** [insomniacslk/dhcp#313]
I see there is a very convenient function called Exchange to run a full DORA transaction. But sometimes on client side, if it found the assigned ip from server side is already being used, so it wants to send a decline message to the server (reject it). And ask server to reassign a different ip to the client. 

In this case, it seems i need to implement the discover , offer, decline, offer, request, acknowledge by myself. Is that right? 

Thanks.

**Comment by hugelgupf** [comment]
Looks like it, but if you look at Exchange - it's not a lot of code, I'd
call it a convenience function. You can use the same stuff to implement
your own.

I think the library and/or client should be as stupid as possible here -
decisions are left to the user. So if you want to make a transaction that
gets declined, I'd use DiscoverOffer and then come up with your own
response.

**Comment by futureday2015** [comment]
Thanks. You are right. I checked the types.go, it has all the options which the dhcp protocol supports, I will implement it myself and can also contribute here if anyone else needs.

**Comment by hugelgupf** [comment]
We'd always take it as library functions!
