### ISSUE TITLE
`server4.NewServer()` does not respect `addr.IP`

### ISSUE THREAD

**Issue by lewisthompson** [insomniacslk/dhcp#326]
In https://github.com/insomniacslk/dhcp/blob/3b29cbd2a47fb7ea9a028ca3bc150f855ae2c5ec/dhcpv4/server4/conn.go#L39-L42:

```go
	// Bind to the port.
	if err := unix.Bind(fd, &unix.SockaddrInet4{Port: port}); err != nil {
		return nil, fmt.Errorf("cannot bind to port %d: %v", port, err)
	}
```

The `Bind` is made only against the specified `port` meaning that the `net.UDPAddr` passed to `NewServer` is partially ignored.

I am attempting to build a DHCP server that supports multiple ranges of IPs.  The only way I understand that I can make this work is to run multiple instances of `server4` where each is bound to a specific interface.  For this to work I need to be able to bind to the configured host IP of each of those interfaces (to avoid `address already in use`).

e.g. if I have `if0 / 192.168.1.1/24` and `if1 / 192.168.2.1/24` I want to launch one `server4` listening on `192.168.1.1:67` on `if0` and another on `192.168.2.1:67` on `if1`.

Am I missing something obvious here or would having `NewIPv4UDPConn` respect the `IP` allow things to work for me?

**Comment by Natolumin** [comment]
> Am I missing something obvious here or would having NewIPv4UDPConn respect the IP allow things to work for me?

There is at least one issue with not listening on the wildcard address: you won't receive broadcasts. Without relays, all the DHCPDISCOVER messages should be broadcast, so basically you won't receive anything.

> I am attempting to build a DHCP server that supports multiple ranges of IPs. The only way I understand that I can make this work is to run multiple instances of server4 where each is bound to a specific interface. For this to work I need to be able to bind to the configured host IP of each of those interfaces (to avoid address already in use).

I do not think that is necessary. The BindToInterface call should ensure you can listen on the wildcard address on multiple sockets on multiple interfaces at the same time, as long as each of the sockets binds to an interface, so it should work to bind on wildcard on each of these interfaces
Here's an excerpt of the sockets on my system which shows that working:
```
$ sudo ip netns exec dhcp_relay ss -lnpu
Local Address:Port      Peer Address:Port
0.0.0.0%cli_u:67              0.0.0.0:*            users:(("coredhcp",pid=20848,fd=9))
0.0.0.0%srv_d:67              0.0.0.0:*            users:(("coredhcp",pid=20848,fd=8))
```
That might, however, be linux-specific behaviour, I'm not sure if the BSDs accept binding multiple sockets to the same address but with different IP_RECVIF options

An alternate solution would be to have relays on the interfaces, that then relay to your (single) real server; then you could build a server that differentiates based on the giaddr (or make your relay add an option 82 and differentiate on that)

**Comment by lewisthompson** [comment]
Thank you for the detailed answer, yes, it does make sense now that you have explained the broadcast.  I also saw that a PR has already been opened despite the extremely limited relay use case - awesome!

Regarding having multiple interfaces bind to the same port on macOS it looks as though the socket needs to have the `SO_REUSEPORT` option set, as per the comment in  https://stackoverflow.com/a/34812994.  Right now just `SO_REUSEADDR` gets set.

I have not yet tested this but will try and do so today and report back.

**Comment by lewisthompson** [comment]
Confirmed: with `SO_REUSEPORT` I can bind multiple times (in this case launching my existing test app twice).

Fortunately I can just use `server4.WithConn()` and just reimplement the `NewIPv4UDPConn()` logic + setting `SO_REUSEPORT` without requiring any upstream changes.

**Comment by pmazzini** [comment]
Do you need to bind to the same interface or different interfaces?

**Comment by lewisthompson** [comment]
Different interfaces.  My local testing shows that even for different interfaces I need `SO_REUSEPORT` though.

**Comment by pmazzini** [comment]
We do respect `addr.IP` after #327. Closing. Reopen if needed.
