### ISSUE TITLE
nclient4 API change proposal: (*Client).Request(...) (discover, offer, request, ack *dhcpv4.DHCPv4, err error)

### ISSUE THREAD

**Issue by xaionaro** [insomniacslk/dhcp#334]
Hello!

The old v4 client (`client4`) has method [Exchange](https://github.com/insomniacslk/dhcp/blob/ec0e0154d15c429b3dcc56af60a2d7b62eb3d5e7/dhcpv4/client4/client.go) which returns 4 messages: `Discover`, `Offer`, `Request` and `Ack`.

While the closest analog in the new v4 client (`nclient4`), method [Request](https://github.com/insomniacslk/dhcp/blob/ec0e0154d15c429b3dcc56af60a2d7b62eb3d5e7/dhcpv4/nclient4/client.go#L331) returns only `Offer` and `Ack`.

And we want to migrate our DHCP dumper from `client4` to `nclient4` and we need all 4 messages. So I have 3 choices:

* To re-implement `Exchange` based on `nclient4` inside our dumper.
* To implement an analog of `Exchange` inside `nclient4`.
* To fix `Request` in `nclient4` to return all 4 messages.

I'd prefer to follow the last variant:

* This is not our specific that it's required to dump all 4 messages. It seems to be quite common task among other companies. So this function should be in the upstream (in `nclient4`).
* Writing another function that does almost the same as `Request` is a duplication of code. We could just fix `Request` and ignore `Discover` and `Request` when they are not needed.

@insomniacslk: What do you think? Should I prepare a PR with the fix for `Request`?

UPD: It will also require to modify `DiscoverOffer` to return both: `Discover` and `Offer`.

**Comment by insomniacslk** [comment]
CC @hugelgupf regarding the changes to nclient4

**Comment by insomniacslk** [comment]
we are also staying on the old client4 for similar reasons

**Comment by pmazzini** [comment]
If this is only for logging I think that the logger interface can be used instead since it prints each packet.

https://github.com/insomniacslk/dhcp/blob/master/dhcpv4/nclient4/client.go#L424

**Comment by xaionaro** [comment]
> If this is only for logging I think that the logger interface can be used instead since it prints each packet.

I wouldn't trust the logging system as to a persistent API.

**Comment by xaionaro** [comment]
@pmazzini : Your way with logger has two advantages:

* It prints messages in real time (instead of printing them all in the ending).
* It prints re-sends of a message.

So I tried to implement both ways here:

https://github.com/insomniacslk/dhcp/pull/335

**Comment by pmazzini** [comment]
Thanks for looking at this!

> So I tried to implement both ways here: #335

Can we have different PRs for the different ways?

**Comment by xaionaro** [comment]
> Can we have different PRs for the different ways?

I've just removed the API-breaking way for a while.

**Comment by pmazzini** [comment]
> I've just removed the API-breaking way for a while.

Thanks

**Comment by xaionaro** [comment]
Not actual anymore, closing for now.
