### ISSUE TITLE
Add probot-auto-merge integration

### ISSUE THREAD

**Issue by insomniacslk** [insomniacslk/dhcp#337]
@hugelgupf and I were talking about integrating https://github.com/bobvanderlinden/probot-auto-merge in this repository, to simplify cases like #333 where the PR has been already approved, and it needs reapproval, which unnecessarily increases the RTT to get it merged. CC @pmazzini for discussion

**Comment by pmazzini** [comment]
> CC @pmazzini for discussion

Sounds good to me.

**Comment by pmazzini** [comment]
Chris has permissions to merge PRs since the referenced issue was opened.
I don't think quick merge of PRs is an issue nowadays.
