### ISSUE TITLE
Compile on Windows

### ISSUE THREAD

**Issue by cretz** [insomniacslk/dhcp#339]
This cannot currently compile on Windows because #267 incorporated `github.com/u-root/u-root/pkg/rand`, which doesn't have a Windows version at https://github.com/u-root/u-root/tree/master/pkg/rand causing:

    vendor\github.com\insomniacslk\dhcp\dhcpv6\dhcpv6message.go:10:2: build constraints exclude all Go files in c:\redacted\vendor\github.com\u-root\u-root\pkg\rand

**Comment by jhawk28** [comment]
#279 would fix this

**Comment by pmazzini** [comment]
* https://github.com/u-root/u-root/pull/2019
* https://github.com/insomniacslk/dhcp/pull/428
* https://github.com/insomniacslk/dhcp/pull/431
