### ISSUE TITLE
DHCP4 client cannot get ip

### ISSUE THREAD

**Issue by chenliu1993** [insomniacslk/dhcp#342]
Hi I am using the this package to get ip from dhcp server for VM. But After I am starting around ten VMs, dhcp client will not get IP anymore. It will returns this error:
client request failed: timed out while listening for replies: unknown

**Comment by chenliu1993** [comment]
In SendReceive Function

**Comment by pmazzini** [comment]
Are you sure this is an issue with the client? Is the server sending a response?

**Comment by chenliu1993** [comment]
Hi I got this error again and do some investigation into it. I found each time this error happens, the client cannot receive the DHCP Offer packet by checking the length of packets list's length of client (which is 1) even server has sent out the Offer packet. Since there is a 3 sec timeout, client will return error after 3 secs if client didn't receive the Offer.

And this is error cannot be reproduced stably.Below are the wireshark output.
![WeChat Screenshot_20200612113447](https://user-images.githubusercontent.com/13761170/84462126-c9e20880-aca0-11ea-8115-dc84dd667e4e.png)

**Comment by pmazzini** [comment]
Can you provide the whole pcap?

**Comment by chenliu1993** [comment]
[wireshark.zip](https://github.com/insomniacslk/dhcp/files/4770918/wireshark.zip)
Yes, the pcapng file is in the zip. And the packet with number 140 is the problem packet. After 140, no further Request packet is sent and another DHCP process begins. Thank you for looking into this.

**Comment by chenliu1993** [comment]
and from the client side, 
```
I can get this timed out while listening for replies with conversation length is 1
```
The first part of this error is generated by Exchange function. The last part of the error is generated by me to show the length of packet lists.

**Comment by pmazzini** [comment]
Is this still an issue?

**Comment by pmazzini** [comment]
Does it happens randomly or is it a constant failure?

**Comment by chenliu1993** [comment]
I don't have the test environment any more, but constant I remember. When the number of request to local DHCP server reached a "number", the above error will show up. And the "number" here is not fixed, but it sure is a big enough number.

**Comment by pmazzini** [comment]
Can you explain a bit more the setup that you have?

Which DHCP server are you using?

Why is the client doing so many requests?

**Comment by chenliu1993** [comment]
Sorry, I am not on this project and can't remember the details. But I can barely remember the reason why the client does so many requests because the veth pair is continuing failing to create so there is always need for a new IP.
The DHCP server is a local server on host since the client is inside a VM

**Comment by chenliu1993** [comment]
Sorry, I am not on this project and can't remember the details. But I can barely remember the reason why the client does so many requests because the veth pair is continuing failing to create so there is always need for a new IP.
The DHCP server is a local server on host since the client is inside a VM
