### ISSUE TITLE
Why are dns mandatory in GetNetConfFromPacketv4

### ISSUE THREAD

**Issue by hexmiles** [insomniacslk/dhcp#359]
I noticied that the function GetNetConfFromPacketv4 return an error if it dosen't find any dns server.
This cause the dhcp client to fail if the server dosen't return any dns server.

is there a reason or is this a bug?

i tried reading the dhcp specs and for what i understand dns are NOT mandatory.

**Comment by pmazzini** [comment]
We may have made it mandatory to be able to resolve URLs names in case one is returned as a boot file url. 

I think the behavior can be changed. Feel free to put up a PR.

Otherwise, we can take a look at it later. Thanks for raising it up.
