### ISSUE TITLE
Custom logger

### ISSUE THREAD

**Issue by tanis2000** [insomniacslk/dhcp#370]
Is there any way to pass to the library a custom logger to use instead of the default "log" package?

**Comment by pmazzini** [comment]
This looks similar to what was discussed in #332.

Which packages are you interested in?

In the nclient4/6 packages you can pass a custom logger.

**Comment by tanis2000** [comment]
@pmazzini thanks for the feedback. Right now I'm interested in the `server4` package and eventually in the `server6`

**Comment by pmazzini** [comment]
Yes, we need to make something similar to what was done for the nclient4/nclient6 packages. Feel free to put up a PR :)

**Comment by tanis2000** [comment]
@pmazzini I'd be happy to contribute that code but so far I noticed that the `master` branch is failing most of the tests. Should I branch from there or is there a branch with no broken tests at the moment? Or is it just a problem because I'm on macOS?

**Comment by pmazzini** [comment]
Yes, it is because of macOS #229 #318

**Comment by tanis2000** [comment]
There you go, this should do the trick: https://github.com/insomniacslk/dhcp/pull/371
Please let me know if you see any issue with it.

**Comment by pmazzini** [comment]
Thanks for working on it.
