### ISSUE TITLE
server4/server6 doesn't closed properly with Close() function

### ISSUE THREAD

**Issue by guo1017138** [insomniacslk/dhcp#376]
Hi,

I am using server4/6 in goroutine(thread) mode, and I may close server4/server6 before exit my main program and do some other task. The Serve() function will return error after Close().

Error reading from packet conn: read udp 0.0.0.0:67: use of closed network connection

It shall be caused by the for loop still there without exit after the server4/6 closed by Close() function, so when try to read the close conn, above error message get printed and returned.

I suggest to enhance the Serve() and Close() function, if Close() is called, the for loop can be stopped before conn get closed.

My code as the following logic:
thread 1:

	go func() {
		s.errors <- s.Server4.Serve()
	}()
	err := <-s.errors
	if s.Server6 != nil {
		s.Server6.Close()
	}
	if s.Server4 != nil {
		s.Server4.Close()
	}
	return err

And I may send signal to stop the thread, and the error message happened after the stop signal sent:

    func (s *Server) Stop() {
	    select {
	    case s.errors <- nil:
	    default:
	    }
    }

**Comment by purpleidea** [comment]
Hi, I suspect this is actually a bug. You can workaround with:

		isClosing := errors.Is(err, net.ErrClosed)

unless we want to keep this behaviour for people to detect. In any case I didn't dig into it, but I can if there is some desire. For now I added the comment for other searchers. HTH
