### ISSUE TITLE
Device or resource busy when requesting from DHCP server using DHCPv4 client

### ISSUE THREAD

**Issue by chenliu1993** [insomniacslk/dhcp#380]
Hi I am using the this package to get ip from dhcp server for VM. But After I am starting around ten VMs, dhcp client will not get IP anymore. It will returns this error:
Device or resource busy.

**Comment by pmazzini** [comment]
Same as #342.

Where is that error appearing? Do you have more logs?

**Comment by chenliu1993** [comment]
Sorry, I notice I may got this error because netlink.LinkSetup(ifname), so maybe my network interface has some issues.
Thank you.
The whole message is `Device or resource busy: invalid argument`
