### ISSUE TITLE
NewRelease() is missing?

### ISSUE THREAD

**Issue by hujun-open** [insomniacslk/dhcp#385]
since nclient4 doesn't support Release exchange, I want to write one, then I was reading doc, the doc for dhcpv4.New() says " See also NewDiscovery, NewOffer, NewRequest, NewAcknowledge, NewInform and **NewRelease** . "
however I can't find NewRelease() in the dhcpv4.go

**Comment by pmazzini** [comment]
> I want to write one

Feel free to create a PR.

**Comment by pmazzini** [comment]
This is a dup of #311. I am going to merge it.

**Comment by pmazzini** [comment]
Feel free to reopen or continue the conversation in #311.
