### ISSUE TITLE
Query on existing code of DHCP

### ISSUE THREAD

**Issue by arun0704** [insomniacslk/dhcp#389]
Would like to know listed functionalities, does code already have?

- API plugin (to control the server via thrift/gRPC/REST/whatever)
- automatic configuration reloader
- plugins to use multiple backends (e.g. mysql)
- plugins to manipulate more DHCP options
- a web UI based on the above API 

And please do comment if any support channel available?

**Comment by pmazzini** [comment]
Short answer is no. It only provides a basic DHCP server library.

For a modular DHCP server you may want to check [coredhcp](https://github.com/coredhcp/coredhcp).
