### ISSUE TITLE
Compile issue in nclient4

### ISSUE THREAD

**Issue by arun0704** [insomniacslk/dhcp#398]
Getting compile-time issue with nclient4 package.

compilepkg: error running subcommand: exit status 2
/private/var/tmp/_bazel_adangi/b9db0c76ac6f90eb1e3650806a8727e9/sandbox/darwin-sandbox/887/execroot/atom/external/com_github_insomniacslk_dhcp/dhcpv4/nclient4/client.go:217:17: undefined: NewRawUDPConn

Code -

c, err := nclient4.NewWithConn(clientConn, iface.HardwareAddr, nclient4.WithServerAddr(saddr))
	if err != nil {
		t.Fatal(err)
	}

I don't call directly "NewRawUDPConn" in code. using code version v0.0.0-20200814125043-2e1bf785d039.
Can someone help me?

**Comment by Natolumin** [comment]
The nclient4 package doesn't support macOS yet (or any non-linux OS). This is more generally tracked in #229 for now

**Comment by pmazzini** [comment]
Lets track this in one issue. Closing in favor of #229.
