### ISSUE TITLE
Gollvm support, including Ubuntu

### ISSUE THREAD

**Issue by advancedwebdeveloper** [insomniacslk/dhcp#401]
Hi.
I wanted to confirm that this projects compiles, tests are running successfully and executables are working - I am using [gollvm](https://go.googlesource.com/gollvm/) on Ubuntu 20.04.1 x86_64 .

I am proposing the maintainers to update your README file and inform people that it could be compiled by "llvm-goc" tool. So there would be some diversification, in choosing which compiler to use.
Besides "official" Go distribution could itself be built using Clang (instead of GCC).

Also hence that [static](https://go.googlesource.com/gollvm/#buildstatic) versions of your tools could be compiled - if that would be of help, for your project.

**Comment by pmazzini** [comment]
Thanks for the info. How do we know if it continues to work?
Are you suggesting to setup a CI with `llvm-goc`?
Are you willing to do this?
