### ISSUE TITLE
No support for non-apple boot menus?

### ISSUE THREAD

**Issue by gmacd** [insomniacslk/dhcp#405]
I've been trying to netboot a raspberry pi 4.  It expects a pxe menu with the string 'Raspberry Pi Boot' (option 43, suboption 9).

The BSDP format used in this code seems to be Apple-specific - in this case, the BootImageID is different.  It would be great if this package could support a non-Apple entry.

I was able to get things working by fiddling with the bytes directly:

```go
dhcpv4.WithOption(dhcpv4.Option{
	Code: dhcpv4.OptionVendorSpecificInformation,
	Value: bsdp.VendorOptions{Options: dhcpv4.OptionsFromList(
		// The dhcp package only seems to support Apple BSDP boot menu items,
		// so we have to craft the option by hand.
		// \x11 is the length of the 'Raspberry Pi Boot' string...
		dhcpv4.OptGeneric(dhcpv4.GenericOptionCode(9), []byte("\000\000\x11Raspberry Pi Boot")),
	)}
```

(Note I'm no expert in this area, so some terms may be wrong, or maybe I missed a better way to achieve the above)

Otherwise thanks for the package!

**Comment by pmazzini** [comment]
Maybe something like this?

```
dhcpv4.WithOption(
        dhcpv4.OptGeneric(dhcpv4.OptionVendorSpecificInformation, dhcpv4.OptionsFromList(
		dhcpv4.OptGeneric(dhcpv4.GenericOptionCode(9), []byte("Raspberry Pi Boot")),
	)}
```

**Comment by pmazzini** [comment]
Reopen if needed.

**Comment by gmacd** [comment]
Sorry, if I use the example you gave, it doesn't work, and I see a malformed packet error in wireshark.  It needs the 3 bytes at the start to fill the structure - it's not just a string.

**Comment by gmacd** [comment]
Looks like I'm unable to reopen this.

**Comment by pmazzini** [comment]
My example is more pseudocode than anything else. Can you provide the example code you are using without the bsdp package and the wireshark capture with the malformed packet?

**Comment by gmacd** [comment]
The actual code is in the text of the issue. I’ll see about the wire shark packet

**Comment by pmazzini** [comment]
> The actual code is in the text of the issue. I’ll see about the wire shark packet

Why are you using the BSDP package?

**Comment by gmacd** [comment]
I couldn't find a better way of creating the pxe menu required to boot a raspberry pi.  I was trying to replicate the message created by dnsmasq as described here: https://www.raspberrypi.org/documentation/hardware/raspberrypi/bootmodes/net_tutorial.md

The dnsmasq config below creates the pxe boot menu I need to replicate:
```
port=0
dhcp-range=10.42.0.255,proxy
log-dhcp
enable-tftp
tftp-root=/tftpboot
pxe-service=0,"Raspberry Pi Boot"
```

The code snippet I posted in the issue does the job, but it feels like there should be a better way.

**Comment by pmazzini** [comment]
Have you looked at my first comment? (which does not use the BSDP package)

**Comment by pmazzini** [comment]
Feel free to reopen it.
