### ISSUE TITLE
dhcpv4: Where is method `NewOffer`

### ISSUE THREAD

**Issue by qin-nz** [insomniacslk/dhcp#416]
Hello, 

I notice in the comment of `dhcpv4.New` method, there should be a method named `NewOffer`. 
I can't find it, it's not implement?

https://github.com/insomniacslk/dhcp/blob/c51060810aaab9c8a0bd1b0fcbf72bc0b91e6427/dhcpv4/dhcpv4.go#L135-L139

**Comment by pmazzini** [comment]
Hi @qin-nz 

The comment of `dhcpv4.New` is wrong. A PR to fix the comment is welcomed.

In a server implementation the Offer gets constructed based on the Discover and the Ack gets constructed based on the Request.

For that we have `NewReplyFromRequest`.

You can check the CoreDHCP example: https://github.com/coredhcp/coredhcp/blob/master/server/handle.go#L119
