### ISSUE TITLE
how to create a dhcp4 server and assign IP address to clients based on subnetmask?

### ISSUE THREAD

**Issue by Gictorbit** [insomniacslk/dhcp#426]
I read the example code provided in documents, but I got confused a little, can you help me?
How can I add DHCP range IP? Should I use handler function or what?

```go
	import (
		"log"
		"net"

		"github.com/insomniacslk/dhcp/dhcpv4"
		"github.com/insomniacslk/dhcp/dhcpv4/server4"
	)

	func handler(conn net.PacketConn, peer net.Addr, m *dhcpv4.DHCPv4) {
		// this function will just print the received DHCPv4 message, without replying
		log.Print(m.Summary())
	}

	func main() {
		laddr := net.UDPAddr{
			IP:   net.ParseIP("127.0.0.1"),
			Port: 67,
		}
		server, err := server4.NewServer("eth0", &laddr, handler)
		if err != nil {
			log.Fatal(err)
		}

		// This never returns. If you want to do other stuff, dump it into a
		// goroutine.
		server.Serve()
	}
```

**Comment by pmazzini** [comment]
This is a "lower level" library and you need to craft the DHCP response packet you want the client to receive.

For a "higher level" server implementation you can look at CoreDHCP.

**Comment by Gictorbit** [comment]
Thank you for your explanation, actually I saw `CoreDHCP` before, but I need an library to use it in my project and I couldn't find any documentation how can I use it in my code as library?

**Comment by pmazzini** [comment]
You can't use `CoreDHCP` as a library, you can only develop plugins for it. Otherwise you can look at its code to see how this library is being used.

**Comment by Gictorbit** [comment]
yeah that's what I did, also I found this library [krolaw/dhcp4](https://github.com/krolaw/dhcp4) useful.
thank you
