### ISSUE TITLE
dhcpv4 malformed packet

### ISSUE THREAD

**Issue by marcj303** [insomniacslk/dhcp#427]
The first packet of fbnetboot dhcpv4 discover fails with a malformed packet. It looks like a problem setting the` User Class Information: linuxboot`. See the attached wireshark pcap.
[userclass_borked.pcapng.gz](https://github.com/insomniacslk/dhcp/files/6533873/userclass_borked.pcapng.gz)

**Comment by pmazzini** [comment]
I haven't looked at the pcap but I suspect this is related to the fact that we support both the RFC compliant user class as defined in RFC3004 and the non RFC compliant as defined by [Microsoft docs](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-dhcpe/a7be26f5-659d-4912-b715-0481b9d84e95?redirectedfrom=MSDN).

Related #113 #114 

[Wireshark info](https://osqa-ask.wireshark.org/questions/35332/dhcp-option-77-malformed-option/?page=1&focusedAnswerId=55006#55006).

We have a bool to set either in the [modifier](https://github.com/insomniacslk/dhcp/blob/master/dhcpv4/modifiers.go#L105).

**Comment by pmazzini** [comment]
`u-root` looks to be using the non RFC compliant one:
https://github.com/u-root/u-root/blob/master/cmds/boot/fbnetboot/main.go#L361

Would you like to check it changing that bool solves your issue?

**Comment by marcj303** [comment]
Yes, Changing fbnetboot to the RFC compliant userclass decodes in wireshark correctly. I guess this issue needs to move to fbnetboot.
