### ISSUE TITLE
dhcpv6: option user class

### ISSUE THREAD

**Issue by pmazzini** [insomniacslk/dhcp#43]
The rfc3315 mentions the following:

>    The data area of the user class option MUST contain one or more
>    instances of user class data.  Each instance of the user class data
>    is formatted as follows:
> 
>       +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-...-+-+-+-+-+-+-+
>       |        user-class-len         |          opaque-data          |
>       +-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-+-...-+-+-+-+-+-+-+
> 
>    The user-class-len is two octets long and specifies the length of the
>    opaque user class data in network byte order.

I think the library is currently only considering the case of having only 1 user class data.

**Comment by insomniacslk** [comment]
you're right - I assumed only one option. This explains the inner length. I am going to make a fix shortly

**Comment by insomniacslk** [comment]
but above all - thanks for spotting it!

**Comment by insomniacslk** [comment]
resolved
