### ISSUE TITLE
panic parsing UDP packet

### ISSUE THREAD

**Issue by smira** [insomniacslk/dhcp#454]
This issue is random, but looks like the library can panic when it receives some (malformed) packet. I don't have the packet dump unfortunately, as the panic happens in the PID 1 process and it crashes whole node.

The panic itself seems to be coming from the line https://github.com/insomniacslk/dhcp/blob/465dd6c35f6c983206a5bc21fbfff4819ce21eb0/dhcpv4/nclient4/ipv4.go#L213, and the panic message is: `panic: runtime error: slice bounds out of range [2:0]`

Looking at the call graph, it seems that the panic originates from the `recieveLoop()` function which runs in a goroutine without panic handler. I'm not sure if the panic got fixed with some later changes to the library, but I propose to add a panic handler to the `receiveLoop` so that it doesn't crash whole Go process. (This can'be be solved outside of the library, as the goroutine is created inside the library). Does this make sense? (I'm happy to work on a PR)

**Comment by smira** [comment]
See also: https://github.com/talos-systems/talos/issues/4567

**Comment by pmazzini** [comment]
Closing after #455
