### ISSUE TITLE
Why are we sorting options during Marshal ? 

### ISSUE THREAD

**Issue by mayuresh82** [insomniacslk/dhcp#460]
Is there a reason why we are sorting the options when marshaling ? 
https://github.com/insomniacslk/dhcp/blob/master/dhcpv4/options.go#L184
This breaks user intent. As a user, I would want the options inserted on the wire in any order I chose. Unfortunately, this also breaks some older vendor implementations that expect options in a specific order.
I cant think of any reason why we would want to sort them this way.

**Comment by pmazzini** [comment]
https://github.com/insomniacslk/dhcp/pull/227#issuecomment-453866068
