### ISSUE TITLE
OptClientArchType does not get the arch field value

### ISSUE THREAD

**Issue by wangliang33** [insomniacslk/dhcp#505]
OptClientArchType only has the string() method externally, and there is no way to obtain the real integer value
<img width="462" alt="image" src="https://github.com/insomniacslk/dhcp/assets/81805454/366df57e-fe4b-4339-ad4f-e0965d461dfd">
<img width="512" alt="image" src="https://github.com/insomniacslk/dhcp/assets/81805454/4030ace2-811b-494e-9e85-048698e3498e">

**Comment by wangliang33** [comment]
Whether OptClientArchType can be visible to the outside world, from optClientArchType to OptClientArchType, so that you can assert to get its value

**Comment by hugelgupf** [comment]
Indeed you are correct.

This getter exists on the right message type to return the value:
https://github.com/insomniacslk/dhcp/blob/b20c9ba983dfec6371555e7baa343aabd388b22c/dhcpv6/dhcpv6message.go#L26

Does that satisfy your use case?

**Comment by wangliang33** [comment]
Thank you
