### ISSUE TITLE
IsOptionRequested does not work with GenericOptionCode

### ISSUE THREAD

**Issue by candlerb** [insomniacslk/dhcp#511]
I was expecting that if I added a GenericOptionCode to a Parameter Request List, then IsOptionRequested() would be able to detect it - but it does not.

Here is a failing test case:

```
--- a/dhcpv4/dhcpv4_test.go
+++ b/dhcpv4/dhcpv4_test.go
@@ -378,6 +378,17 @@ func TestIsOptionRequested(t *testing.T) {
        require.True(t, pkt.IsOptionRequested(OptionDomainNameServer))
 }

+func TestIsGenericOptionRequested(t *testing.T) {
+       pkt, err := New()
+       require.NoError(t, err)
+
+       var optionV6OnlyPreferred GenericOptionCode = 108
+       pkt.UpdateOption(OptParameterRequestList(OptionBroadcastAddress, optionV6OnlyPreferred))
+       require.True(t, pkt.IsOptionRequested(OptionBroadcastAddress))
+       require.False(t, pkt.IsOptionRequested(OptionSwapServer))
+       require.True(t, pkt.IsOptionRequested(optionV6OnlyPreferred), "Did not detect generic option in %v", pkt.ParameterRequestList())
+}
+
 // TODO
 //      test Summary() and String()
 func TestSummary(t *testing.T) {
```

(This example uses option code 108, from RFC8925, which is not provided as a predefined OptionCode)

**Comment by pmazzini** [comment]
I think this is because you are defining an option with a different type:

https://github.com/insomniacslk/dhcp/blob/master/dhcpv6/dhcpv6message.go#L147

**Comment by pmazzini** [comment]
> (This example uses option code 108, from RFC8925, which is not provided as a predefined OptionCode)

It is in here: https://github.com/insomniacslk/dhcp/blob/master/dhcpv4/types.go#L242

**Comment by candlerb** [comment]
I got it added in #524 :-)

But I think the point about detecting GenericOptionCodes still stands.

**Comment by pmazzini** [comment]
I think this is because you are comparing `optionCode` against `GenericOptionCode`, different types.

https://github.com/insomniacslk/dhcp/blob/master/dhcpv4/dhcpv4.go#L486

**Comment by candlerb** [comment]
Certainly it may be a question of expectations and/or documentation. However, I note that:

* `IsOptionRequested` takes an `OptionCode` as its argument, not an `optionCode`
* `OptionCode` is an [interface](https://github.com/insomniacslk/dhcp/blob/master/dhcpv4/types.go#L100)
* The `OptionCode` interface is implemented by both [optionCode](https://github.com/insomniacslk/dhcp/blob/master/dhcpv4/types.go#L111-L122) and [GenericOptionCode](https://github.com/insomniacslk/dhcp/blob/master/dhcpv4/types.go#L127-L135)

Therefore, it was my expectation that this function would work for any argument implementing the OptionCode interface (and AFAIK there's no other way to generate a custom `optionCode` value, since it's a private type).

What if the comparison were changed to `o.Code() == requested.Code()` ?
