### ISSUE TITLE
dhcpv6 mask and gateway

### ISSUE THREAD

**Issue by sprootik** [insomniacslk/dhcp#527]
Hello.
I can’t understand how to transfer the mask and gateway for v6. If I understand correctly, you can only pass the address /128.

**Comment by pmazzini** [comment]
That information is passed via the Router Advertisement.

**Comment by sprootik** [comment]
> That information is passed via the Router Advertisement.

Thanks. I used WithIANA modifier for func NewAdvertiseFromSolicit or NewRequestFromAdvertise. But WithIANA have only net.IP.
I don't understand how to pass the prefix length and gateway. Could you give me some advice?

**Comment by hugelgupf** [comment]
router advertisements are not part of DHCPv6. The config is supposed to come via NDP router advertisements.
