### ISSUE TITLE
Can DHCP Server detect client windows version?

### ISSUE THREAD

**Issue by javad9505** [insomniacslk/dhcp#539]
I have a DHCP server and several clients, some running Windows 10 and some Windows 7. I wuant the DHCP server to be able to identify the Windows version of the clients using the vendor class and assign the settings I've specified accordingly. Also, I don't want to configure anything on the clients; I want the DHCP server to be able to detect the Windows version by itself. Is there a way to do this?

**Comment by pmazzini** [comment]
Is the client sending any information for the server to be able to identify the Windows version?

**Comment by javad9505** [comment]
client send VCI(vendor class identifier) to server but for windows 10 and 7 is equal.

**Comment by pmazzini** [comment]
> but for windows 10 and 7 is equal

Then there is your answer. If there is nothing in the packet to distinguish between Windows versions, then the DHCP server won't be able to.

**Comment by pmazzini** [comment]
Closing. Feel free to reopen.
