### ISSUE TITLE
Add integration tests

### ISSUE THREAD

**Issue by insomniacslk** [insomniacslk/dhcp#82]
There are several parts (client, server) that can't be easily tested with unit tests in Go. Let's add integration tests to fill the gap

**Comment by insomniacslk** [comment]
Ginkgo was suggested for integ tests, https://onsi.github.io/ginkgo/

**Comment by pmazzini** [comment]
For reference, we now how some integration tests: https://github.com/insomniacslk/dhcp/blob/master/netboot/netconf_integ_test.go

**Comment by pmazzini** [comment]
We have some integration tests.
